##### In this run we are going to read in the 1=7000 results files generated by the HPC run 
# we are going to look at all the resultant PD losses and and create a 'master' edge scores data-frame

# Housekeeping
rm(list=ls())
graphics.off()
#setwd("C:\Users\oenon\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\oslin")
getwd()
# set it as the linux machine - but have to use windows navigation as accessing through windows. GRIM!
setwd("../../../oenon/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/home/oslin/EDGE2/")

# first things first: packages

library(ape)
library(caper)
library(data.table)
require(geiger)
require(pez)
require(phytools)
require(phylobase)

## now lets IMPORT THOSE DATAAAAAAAAAAAAA
### set up the storage devices

# each result has three lists, each of which has one entry
# ideally we don't want millions of lists, we'd like: 
# one list with 1000 trees, one DF with 1000 EDGE2 scores and one DF with 1000 ED scores

f.EDGE.2.list <- list()
f.exp.PD.list <- data.frame(Tree = c(1:1000), PD = NA, ePDloss = NA, ePD = NA)
f.exp.PD.trees <- list()


# for everything BUT Act:

prefix <- c("Bird", "Ch", "Sq", "Am")

results <- list(Bird = NA, Ch = NA, Sq = NA, Am = NA)
  # do this manually, for saving reasons
  x <- 4
  for (i in 1:1000) {
      EDGE.2.list <- NA
      exp.PD.list <- NA
      exp.PD.trees <- NA
      to.load <- paste("UnzippedResults/", prefix[x], "_New_EDGE2_", i, "_.Rdata", sep = "")
      try(load(file = to.load), silent = F) # called res
      f.EDGE.2.list[[i]] <- EDGE.2.list[[1]]
      f.exp.PD.list[i,c(2:4)] <- exp.PD.list[[1]]
      f.exp.PD.trees[[i]] <- exp.PD.trees[[1]]
      if (i %% 100 == 0) { 
        print(paste(x,i))
      }}
  
  
  
  Am_EDGE.2.lists <- f.EDGE.2.list
  Am_exPD <- f.exp.PD.list
  Am_Trees <- f.exp.PD.trees
  
  save(Am_EDGE.2.lists, file = "EDGE2_ConsolidatedResults/Am_EDGE2lists.Rdata")
  save(Am_exPD, file = "EDGE2_ConsolidatedResults/Am_exPD.Rdata")
  save(Am_Trees, file = "EDGE2_ConsolidatedResults/Am_EDGE2Trees.Rdata")
  
  
  Sq_EDGE.2.lists <- f.EDGE.2.list
  Sq_exPD <- f.exp.PD.list
  Sq_Trees <- f.exp.PD.trees
  
  save(Sq_EDGE.2.lists, file = "EDGE2_ConsolidatedResults/Sq_EDGE2lists.Rdata")
  save(Sq_exPD, file = "EDGE2_ConsolidatedResults/Sq_exPD.Rdata")
  save(Sq_Trees, file = "EDGE2_ConsolidatedResults/Sq_EDGE2Trees.Rdata")
  
  
  
  #Sharks <- list()
  #Sharks$EDGE.2.lists <- f.EDGE.2.list
  #Sharks$exPD <- f.exp.PD.list
  #Sharks$Trees <- f.exp.PD.trees
  #save(Sharks, file = "EDGE2_ConsolidatedResults/EDGE2_Sharks.Rdata")
  
  #Birds <- list()
  #Birds$EDGE.2.lists <- f.EDGE.2.list
  #Birds$exPD <- f.exp.PD.list
  #Birds$Trees <- f.exp.PD.trees
  
  #save(Birds, file = "EDGE2_ConsolidatedResults/EDGE2_Birds.Rdata")
  



# check where the NAs are

na.results <- list(Bird = NA, Ch = NA, Sq = NA, Am = NA)


for (x in 1:length(prefix)) {
  counter <- NA
  for (i in 1:1000) {
    EDGE.2.list <- NA
    exp.PD.list <- NA
    exp.PD.trees <- NA
    to.load <- paste("UnzippedResults/", prefix[x], "_New_EDGE2_", i, "_.Rdata", sep = "")
    try(load(file = to.load), silent = T) # called res
    if (length(EDGE.2.list[[1]]) == 1) {
      counter <- c(counter,i)
    }
     if (i %% 100 == 0) { 
      print(paste(x,i))
    }
  }
  na.results[[x]] <- counter
  
}
# Birds and Sharks are fine, Squamates and Amphibians have some 


# remove the intial NAs
na.results$Sq <- na.results$Sq[-1]
na.results$Am <- na.results$Am[-1]
save(na.results, file = "NaResults.Rdata")

## finally, read in the fish data

f.EDGE.2.list <- list()
f.exp.PD.list <- data.frame(Tree = c(1:2000), PD = NA, ePDloss = NA, ePD = NA)
f.exp.PD.trees <- list()

for (i in 1:2000) {
  EDGE.2.list <- NA
  exp.PD.list <- NA
  exp.PD.trees <- NA
  to.load <- paste("UnzippedResults/Act_New_EDGE22_Isaac_", i, "_.Rdata", sep = "")
  try(load(file = to.load), silent = F) # called res
  f.EDGE.2.list[[i]] <- EDGE.2.list[[1]]
  f.exp.PD.list[i,c(2:4)] <- exp.PD.list[[1]]
  f.exp.PD.trees[[i]] <- exp.PD.trees[[1]]
  if (i %% 100 == 0) { 
    print(paste(i))
  }}


# check fish NAs & remove them

fish.na <- NA

for (i in 1:2000) {
  EDGE.2.list <- NA
  exp.PD.list <- NA
  exp.PD.trees <- NA
  to.load <- paste("UnzippedResults/Act_New_EDGE22_Isaac_", i, "_.Rdata", sep = "")
  try(load(file = to.load), silent = T) # called res
  if (length(EDGE.2.list[[1]]) == 1) {
    fish.na <- c(fish.na,i)
  }
  if (i %% 100 == 0) { 
    print(paste(x,i))
  }
}

fish.na <- fish.na[-1]
save(fish.na, file = "FishNas.Rdata")

Fish_EDGE.2.lists <- f.EDGE.2.list[-fish.na]
Fish_exPD <- f.exp.PD.list[-fish.na]
Fish_Trees <- f.exp.PD.trees[-fish.na]

# now cut down to the first 1000

Fish_EDGE.2.lists <- Fish_EDGE.2.lists[c(1:1000)]
Fish_exPD <- Fish_exPD[c(1:1000)]
Fish_Trees <- Fish_Trees[c(1:1000)]

save(Fish_EDGE.2.lists, file = "EDGE2_ConsolidatedResults/Fish_EDGE2lists.Rdata")
save(Fish_exPD, file = "EDGE2_ConsolidatedResults/Fish_exPD.Rdata")
save(Fish_Trees, file = "EDGE2_ConsolidatedResults/Fish_EDGE2Trees.Rdata")

# now re-read in sharks & birds and seperate the files

load("EDGE2_ConsolidatedResults/EDGE2_Sharks.Rdata")

Shark_EDGE.2.lists <- Sharks$EDGE.2.lists
Shark_exPD <- Sharks$exPD
Shark_Trees <- Sharks$Trees

save(Shark_EDGE.2.lists, file = "EDGE2_ConsolidatedResults/Shark_EDGE2lists.Rdata")
save(Shark_exPD, file = "EDGE2_ConsolidatedResults/Shark_exPD.Rdata")
save(Shark_Trees, file = "EDGE2_ConsolidatedResults/Shark_EDGE2Trees.Rdata")

# and birds

load("EDGE2_ConsolidatedResults/EDGE2_Birds.Rdata")

Birds_EDGE.2.lists <- Birds$EDGE.2.lists
Birds_exPD <- Birds$exPD
Birds_Trees <- Birds$Trees

save(Birds_EDGE.2.lists, file = "EDGE2_ConsolidatedResults/Birds_EDGE2lists.Rdata")
save(Birds_exPD, file = "EDGE2_ConsolidatedResults/Birds_exPD.Rdata")
save(Birds_Trees, file = "EDGE2_ConsolidatedResults/Birds_EDGE2Trees.Rdata")


load("NaResults.Rdata")


# checking some other data for Riki 

rm(list = ls())

load("D:/Documents/ResearchProject/Data/ActSpeciesGE.Rdata")


